### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by lm-jkominek** [jantonio-garciamartin/jdet#2]
Hi there, @jantonio-garciamartin ,thanks for making JDet, it's a great tool! 
The only issue I have with it is that it is not parallelized, so a single alignment analysis can take up to an hour on my end. I know it's been long size you last worked on this, but I just thought I'd ask if you had any plans for that or, alternatively, could suggest a different tool that could do unsupervised SDP assessment at scale? 
Thanks in advance, all the best!

**Comment by jantonio-garciamartin** [comment]
Hi, we are not planning to add parallelization, as the SDP assessment methods included (Xdet, S3det) are not prepared to do so.
